/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlayChip {
        "delete": boolean;
        "disabled": boolean;
        "icon": string;
        "label": string;
        "outlined": boolean;
    }
}
declare global {
    interface HTMLPlayChipElement extends Components.PlayChip, HTMLStencilElement {
    }
    var HTMLPlayChipElement: {
        prototype: HTMLPlayChipElement;
        new (): HTMLPlayChipElement;
    };
    interface HTMLElementTagNameMap {
        "play-chip": HTMLPlayChipElement;
    }
}
declare namespace LocalJSX {
    interface PlayChip {
        "delete"?: boolean;
        "disabled"?: boolean;
        "icon"?: string;
        "label"?: string;
        "outlined"?: boolean;
    }
    interface IntrinsicElements {
        "play-chip": PlayChip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "play-chip": LocalJSX.PlayChip & JSXBase.HTMLAttributes<HTMLPlayChipElement>;
        }
    }
}
